name: Deploy to WP Engine
on:
  push:
    branches:
     - develop
jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3.0
      with:
      # Deploy vars 
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        WPE_ENV: STG_ENV
        # Deploy Options
        # SRC_PATH: "wp-content/themes/asianlegacylibrary-wp/"
        REMOTE_PATH: "wp-content/themes/asianlegacylibrary-wp/"
        # PHP_LINT: TRUE
        FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
        # SCRIPT: "path/yourscript.sh"
        CACHE_CLEAR: TRUE
