name: Deploy to DEV (asianlegacydev) on WP Engine
on:
    push:
        branches:
            - develop
env:
    WPE_SERVER: asianlegacydev
    WP_CONTENT_FOLDER: themes
    WP_PLUGIN_NAME: asianlegacylibrary-wp
    BASH_SCRIPT_NAME: deploy_development.sh
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: GitHub Action Deploy to WP Engine
              uses: wpengine/github-action-wpe-site-deploy@v3.0
              with:
                  # Deploy vars
                  WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
                  WPE_ENV: ${{ env.WPE_SERVER }}
                  # Deploy Options
                  # SRC_PATH: "wp-content/themes/asianlegacylibrary-wp/"
                  REMOTE_PATH: 'wp-content/${{ env.WP_CONTENT_FOLDER }}/${{ env.WP_PLUGIN_NAME }}/'
                  PHP_LINT: TRUE
                  FLAGS: -azvr --inplace --delete --exclude=".*" --exclude="node_modules"
                  # --exclude-from=.deployignore
                  SCRIPT: 'wp-content/${{ env.WP_CONTENT_FOLDER }}/${{ env.WP_PLUGIN_NAME }}/deploy-scripts/${{ env.BASH_SCRIPT_NAME }}'
                  CACHE_CLEAR: TRUE
