name: Deploy to PROD (asianlegacylib) on WP Engine
on:
    push:
        branches:
            - production
env:
    WPE_SERVER: asianlegacylib
    WP_CONTENT_FOLDER: themes
    WP_PLUGIN_NAME: asianlegacylibrary-wp
    BASH_SCRIPT_NAME: deploy_production.sh
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: GitHub Action Deploy to WP Engine
              uses: wpengine/github-action-wpe-site-deploy@v3
              with:
                  WPE_SSHG_KEY_PRIVATE: ${{ secrets.PROD_WPE_SSHG_KEY_PRIVATE }}
                  WPE_ENV: ${{ env.WPE_SERVER }}
                  REMOTE_PATH: 'wp-content/${{ env.WP_CONTENT_FOLDER }}/${{ env.WP_PLUGIN_NAME }}/'
                  PHP_LINT: TRUE
                  FLAGS: -azvr --inplace --delete --exclude=".*" --exclude="node_modules"
                  SCRIPT: 'wp-content/${{ env.WP_CONTENT_FOLDER }}/${{ env.WP_PLUGIN_NAME }}/deploy-scripts/${{ env.BASH_SCRIPT_NAME }}'
                  CACHE_CLEAR: TRUE
